### PR TITLE
Return value on @property decorator

### PR DESCRIPTION
**Pull request by kienpham2000**
Alexa team rejected my skill due to missing verification. I traced and these values never get set.

### CODE REVIEW

**Comment by johnwheeler** [comment]
Yikes! That's a biggie. It looks like the code got ripped out of a commit. I'll patch it tomorrow and release a new version. There's an alternative means I set the config

**Comment by johnwheeler** [comment]
Actually, this looks good. Thank you for the PR. I'll do a version bump to PyPi tomorrow.

**Comment by kienpham2000** [comment]
cool can you tag github too?

**Comment by johnwheeler** [comment]
Do you tag every time I do a release from now on? If so, I can do that.

**Comment by johnwheeler** [comment]
Sorry, miswrote:

Do you *mean* tag every time I do a release from now on? If so, I can do that.

**Comment by kienpham2000** [comment]
yea I think it would be very helpful whenever you release a version to pypi, you also tag github so it's easier to see the diff from version to version.

**Comment by johnwheeler** [comment]
Yes - for sure. Thanks again Kien

**Pull request merged**
