### PR TITLE
Streaming audio

### PR DESCRIPTION
**Pull request by treethought**
Hey John,
I've put together an interface for sending AudioPlayer Directives within a response.
I've also added callback functions for AudioPlayerRequests in a similar matter to Intent view functions for IntentRequests. To do this, I refactored _map_intent_to_view_func and split it into a method for each request type.
The new additions can be tested with the ask_audio.py example.

Thanks,
Cam

### CODE REVIEW

**Comment by johnwheeler** [comment]
Thanks Cam. This is beautiful work in the spirit of the existing interfaces. I've made you a collaborator on this project, so you should be able to do direct commits from now on.

**Comment by johnwheeler** [comment]
I'm testing this, then I'll merge into master

**Comment by treethought** [comment]
That's great to hear, thank you! Really looking forward to seeing how this
project grows.

**Comment by johnwheeler** [comment]
Smiles from ear to ear. This is fantastic with your sample. Thanks so much for this.

**Comment by treethought** [comment]
Hahaha, glad you like it. :)

**Comment by johnwheeler** [comment]
For sure! Merged, version bumped, and cut a new release to pypi 0.8.0. Don't be shy and feel free to contribute as much or as little as you want.

**Comment by treethought** [comment]
Awesome! Thanks a lot, I'm excited to help out.

**Comment by johnwheeler** [comment]
I'm still not super familiar with the audio stuff (i'm piecing it together based on your work).

Do you know if these structures redundant at this point?

```
class _Context(object):pass
class _System(object):pass
class _AudioPlayer(object):pass
class _Device(object):pass
class _SupportedInterfaces(object):pass
```

**Comment by treethought** [comment]
They might be. They basically just allow an object with attributes to be passed within the request body. They could maybe all be an instance of a bare class. They do help with debugging though.
I was considering some type of basic class that accepts a dict.

```
class _Stream(object):
     def __init__(self, stream_dict=None):
         if stream_dict:
             self.__dict__.update(stream_dict)
```
But wasn't sure if that was unnecessary,  and instead just called update() on the current stream object when modifying. 

I didn't deal with the system, device, or interface objects though.

**Comment by foxy82** [comment]
Hey guys,

Great work on this and thanks for your efforts. I've tried to use the audio bits to allow me to play a playlist but the call backs like nearly finished don't seem to work very well....

Firstly the example in the code:
@ask.on_playback_nearly_finished
def play_next_stream():
            audio().enqueue(my_next_song)

This doesn't work as the method is never called I had to add parameters as such:
@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number': 'token'})

to get it to be called.

Now running this I get:

[2016-11-05 15:12:49,645] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "gmusic_player.py", line 206, in play_next_stream
    audio().enqueue(my_next_song)
TypeError: __init__() missing 1 required positional argument: 'speech'


So I add some speech in...
audio("Next").enqueue(my_next_song)

Now I get this:

[2016-11-05 15:15:20,362] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "gmusic_player.py", line 206, in play_next_stream
    audio("Next").enqueue(my_next_song)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 636, in enqueue
    audio_item['stream']['expectedPreviousToken'] = audio.prev_stream.token
AttributeError: type object 'audio' has no attribute 'prev_stream'

So I try play_next... and again fails with no speech:

[2016-11-05 15:17:17,751] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "gmusic_player.py", line 205, in play_next_stream
    audio().play_next(my_next_song)
TypeError: __init__() missing 1 required positional argument: 'speech'


So I add some speech... and now I get this error:

[2016-11-05 15:21:19,511] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 431, in _flask_view_func
    return result.render_response()
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 566, in render_response
    'sessionAttributes': session.attributes
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_Session' object has no attribute 'attributes'

**Comment by foxy82** [comment]
These are all the things I've tried as code based on the sample:

`# The example in the code is never called
#@ask.on_playback_nearly_finished
#def play_next_stream():
#  print("Nearly Fininshed")
#  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
#  audio().enqueue(stream_url)


# Error no speech
#@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number':'token'})
#def play_next_stream():
#  print("Nearly Fininshed")
#  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
#  audio().enqueue(stream_url)


# Error AttributeError: type object 'audio' has no attribute 'prev_stream'
#@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number':'token'})
#def play_next_stream():
#  print("Nearly Fininshed")
#  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
#  audio("Next").enqueue(stream_url)


# Error no speech
#@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number':'token'})
#def play_next_stream():
#  print("Nearly Fininshed")
#  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
#  audio().play_next(stream_url)


# This plays and finishes but the next song doesn't start
#@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number':'token'})
#def play_next_stream():
#  print("Nearly Fininshed")
#  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
#  audio("Next").play_next(stream_url)


# Try with return but get error AttributeError: '_Session' object has no attribute 'attributes'
@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number':'token'})
def play_next_stream():
  print("Nearly Fininshed")
  stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
  return audio("Next").play_next(stream_url)
`

**Comment by foxy82** [comment]
[ask_audio.py.txt](https://github.com/johnwheeler/flask-ask/files/573320/ask_audio.py.txt)

As a file instead...

**Comment by treethought** [comment]
Hey foxy, thanks for bringing this up. Sorry it's causing you some
problems. I'll be home in a couple of hours and will definitely take a look.

I noticed one thing that may be causing an error though. when forming a
response to the on playback requests, Alexa does not allow any speech
output to be provided. It only allows for audio directives.
It seems there's some more issues going on though. I'll get back to you
when I get a chance to look.

**Comment by foxy82** [comment]
Thanks Cam,

You obviously don't owe me anything so I really appreciate it!!

**Pull request merged**
