### PR TITLE
Fix the issue #137

### PR DESCRIPTION
**Pull request by Christina96**
For running correctly on Windows was needed to add two variables in env (subprocess.Popen ())

### CODE REVIEW

**Comment by Christina96** [comment]
Yes of course. Do you want to put them in comment like:
```
self.env = {'PYTHONPATH': project_root,
            'ASK_VERIFY_REQUESTS': 'false'}
            # On Windows environment it also needs the valiables: 'SYSTEMROOT': os.getenv('SYSTEMROOT') and 'PATH': os.getenv('PATH')
```

**Comment by voutilad** [comment]
It could be as simple as checking if the OS is Windows (one way is the platform module's [platform()](https://docs.python.org/3.6/library/platform.html#platform.platform) function). If it's running on Windows, then we update the `self.env` dict to add the SYSTEMROOT and PATH like you did in your original change.

If you want to add a comment, it's best to say Python will crash on Windows without setting those environment variables.

**Comment by Christina96** [comment]
If you run only one of the samples test for example helloword.py everything looks fine. **But** if you try to run all the sample test then Failed. That's because keeps the first request and every time takes the same JSON. I think that we can fix it with `request.delete(url, json=data)`

**Comment by voutilad** [comment]
Huh, well that might require future investigation. I think we can merge this for now since it resolves the first underlying issue of the hard crash of `subprocess.Popen()` spawned Python instances. If there's a platform bug in the test logic we can track that separately.

**Comment by Christina96** [comment]
I've seen a few things, and I've also read some reports that mention this as a bug on windows. I tried to fix it, but I did not. I will see it again in the future.

**Pull request merged**
