### PR TITLE
Add support for using Flask Blueprints

### PR DESCRIPTION
**Pull request by voutilad**
While experimenting with Flask-Ask, I was trying to wire it into an app that already uses Blueprints. Since Blueprints aren't supported I figured I'd take a crack at extending Flask-Ask to make it work.

There are some design assumptions, specifically that there's only 1 Ask instance. This mirrors the current design where there's only 1 instance per Flask App. 

Also, I had to refactor how the ASK settings get read (e.g. `ASK_VERIFY_REQUESTS`). Since the Blueprint doesn't have easy access to the App, I made the properties on the `Ask` class so they get read on-the-fly from referencing `current_app`.

I've added a new sample application (`blueprint_demo`) that illustrates using Blueprints with Flask-Ask.

### CODE REVIEW

**Comment by johnwheeler** [comment]
Wow voutilad! Thank you for this P.R. It looks good. I'm going to test it tomorrow or the next day, and then we'll merge.

Thank you so much!

**Comment by johnwheeler** [comment]
Hi Dave,

I'm testing this now. I've never used blueprints before, and while I've heard of them, I don't really understand them, so bear with me.

I'm using ngrok to test your demo, and if I omit a trailing slash in the Alexa configuration on the dashboard Amazon provides, I get:

```
FormDataRoutingRedirect: A request was sent to this URL (http://b83fdd23.ngrok.io/ask) but a redirect was issued automatically by the routing system to "http://b83fdd23.ngrok.io/ask/".  The URL was defined with a trailing slash so Flask will automatically redirect to the URL with the trailing slash if it was accessed without one.  Make sure to directly send your POST-request to this URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.
```

If I put a trailing slash in the configuration, it works.

In the demo, you have omitted the trailing slash

```
blueprint = Blueprint('blueprint_api', __name__, url_prefix="/ask")
```

So long as there's a trailing slash in the Amazon dashboard configuration, it doesn't matter if there is a trailing slash in `url_prefix` or not.

I'm wondering if this trailing slash redirection has anything to do with this code?

```
 # make sure we set the rule to "/" so the Blueprint's url_prefix works, otherwise we can
 # end up with things like "/ask/ask" when we only want "/ask"
 blueprint.add_url_rule("/", view_func=self._flask_view_func, methods=['POST'])
```

or is it just standard blueprint stuff I need not be concerned with? Ultimately, I think it'd be nice to respect whatever URL is specified as `url_prefix`, so API users don't get confused and generate issues.

Thoughts?

And thanks!

**Comment by voutilad** [comment]
Most likely. Good find.

I'm also just finding an issue using templates. Working on resolving that now.

I'll see if dropping that slash fixes the trailing slash issue. Most likely does.

Definitely hold off on merging for now.

**Comment by voutilad** [comment]
I think I resolved both issues as luckily they were trivial. 

For the trailing slash, it seems Blueprints end up doing some concatenation under the covers, so it was simply setting that literal `"/"` to an empty string.

As for the templates, it turns out Blueprints don't have a `jinja_loader` attribute, so I was adding a `None` into the `ChoiceLoader` loader list.

**Comment by johnwheeler** [comment]
Thanks again Dave!

**Pull request merged**
