### PR TITLE
Support for Dialog Deligation

### PR DESCRIPTION
**Pull request by pramodmauryaiiita**
Issue #125

### CODE REVIEW

**Comment by pramodmauryaiiita** [comment]
raising a new PR with with fewer commits

**Comment by bsouthern** [comment]
how are we supposed to return a delegate object? I cannot figure out how to make this new class do anything with the dialog interface amazon provides

**Comment by pramodmauryaiiita** [comment]
```
request_data = json.loads(request.data)
if session["dialogState"] != "COMPLETED":
    return delegate(request_data['request'])
```
this way you can use delegates

**Comment by Pradhyo** [comment]
Why the `speech` parameter in models.py?
I had copied this code before it was merged into master but now just returning `delegate()` broke my code when I updated flask-ask

I had `def __init__(self):` instead of `def __init__(self, speech):` from below

```
class delegate(_Response):

    def __init__(self, speech):
        self._response = {
            'shouldEndSession': False,
            'directives': [{'type': 'Dialog.Delegate'}]
        }

```

**Pull request closed without merging**
