### PR TITLE
Include __str__ method on statement & question models

### PR DESCRIPTION
**Pull request by mafrosis**
A couple of convenience methods for development

### CODE REVIEW

**Comment by johnwheeler** [comment]
Seems like it should be implemented on _Response instead of the two subclasses. Thoughts?

**Comment by mafrosis** [comment]
Absolutely it should!

**Comment by mafrosis** [comment]
@johnwheeler any reason this was closed? I moved the `__str__` method to `_Response` class.

**Comment by johnwheeler** [comment]
Hi, I decided not to incorporate it because it doesn't make sense for all potential response subclasses. For example, there's currently one called `audio` that might not have the speech field set, and it doesn't really make sense in that case to return speech for `__str__` even if it does. 

I know I asked you to put it on Response, but that was not a good suggestion. Instead, each subclass should probably have its own implementation of `__str__`. Sorry for confusion and bad communication. I guess I haven't really thought the issue through and closed the PR in haste while closing others in housecleaning.

**Comment by mafrosis** [comment]
Hey no problem. I haven't looked at Alexa stuff since Jan!

If I move the `__str__` method back to the `Statement` class will it get merged? I guess the pythonic implementation would be to add `__repr__` to all classes as appropriate, and also add `__str__` to `Statement`.

(I haven't actually looked at any of the other classes such as `audio`!)

**Pull request closed without merging**
