### PR TITLE
Support for Dialog Deligation

### PR DESCRIPTION
**Pull request by pramodmauryaiiita**
Issue #125

### CODE REVIEW

**Comment by johnwheeler** [comment]
Thank you!

**Comment by georgymh** [comment]
Would love to see this feature on PyPI. Any idea when a new version will be pushed?

Thanks!

**Comment by johnwheeler** [comment]
Updated to 0.9.7 which includes your PR. Thanks again

**Comment by Kcrong** [comment]
@johnwheeler Hi, I'm trying to use this feature, but I couldn't find related to this pull request. how can I use `deligation` for slot filling?

**Pull request merged**
